[cmake] CheckPlatform correctly check correct x86_64 variable
Windows SDK's dont look like they have _X64_ defined in Windows.h.
I checked back until win 7 sdk's. They all do have _AMD64_ that says
it is x86_64.
Remove the unnecessary symbol check for _X64_ and rename the output of
_AMD64_ to WIN64.

Kodi was patching _USE_32BIT_TIME_T to avoid the following errors when
building for x86_64. Time to properly fix the root cause

14:06:19 C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt.h(634,1): error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_TIME_T) with _WIN64 [C:\jenkws\workspace\WIN-64\kodi-build.x64\build\cec\src\cec-build\src\libcec\cec.vcxproj] [C:\jenkws\workspace\WIN-64\kodi-build.x64\cec.vcxproj]
14:06:19     (compiling source file '../../../cec/src/libcec/CECProcessor.cpp')
14:06:19
14:06:19 C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt.h(634,1): error C1189: #error:  You cannot use 32-bit time_t (_USE_32BIT_TIME_T) with _WIN64 [C:\jenkws\workspace\WIN-64\kodi-build.x64\build\cec\src\cec-build\src\libcec\cec.vcxproj] [C:\jenkws\workspace\WIN-64\kodi-build.x64\cec.vcxproj]
14:06:19     (compiling source file '../../../cec/src/libcec/CECClient.cpp')